use default location for authfile

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -1,12 +1,12 @@
 #!/bin/sh
 
-if [ -z "${MNTPOINT}" ] || [ -z "${AUTHFILE}" ] || [ -z "${SURL}" ]
+if [ -z "${MNTPOINT}" ] || [ -z "${SURL}" ]
 then
-	echo "missing \$MNTPOINT \$AUTHFILE or \$SURL"
+	echo "missing \$MNTPOINT or \$SURL"
 	exit 1
 fi
 
-if ! mount.s3ql --fg --authfile ${AUTHFILE} ${SURL} ${MNTPOINT}
+if ! mount.s3ql --fg ${SURL} ${MNTPOINT}
 then
 	echo "unable to mount fs" >& 2
 	exit 1
